/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WImport } from './routes/w'
import { Route as AuthImport } from './routes/auth'
import { Route as AppImport } from './routes/_app'
import { Route as AppIndexImport } from './routes/_app.index'
import { Route as AuthTwitchCallbackImport } from './routes/auth.twitch-callback'
import { Route as AppSettingsImport } from './routes/_app.settings'
import { Route as AppModerationImport } from './routes/_app.moderation'

// Create/Update Routes

const WRoute = WImport.update({
  path: '/w',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  path: '/auth',
  getParentRoute: () => rootRoute,
} as any)

const AppRoute = AppImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const AppIndexRoute = AppIndexImport.update({
  path: '/',
  getParentRoute: () => AppRoute,
} as any)

const AuthTwitchCallbackRoute = AuthTwitchCallbackImport.update({
  path: '/twitch-callback',
  getParentRoute: () => AuthRoute,
} as any)

const AppSettingsRoute = AppSettingsImport.update({
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)

const AppModerationRoute = AppModerationImport.update({
  path: '/moderation',
  getParentRoute: () => AppRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/w': {
      id: '/w'
      path: '/w'
      fullPath: '/w'
      preLoaderRoute: typeof WImport
      parentRoute: typeof rootRoute
    }
    '/_app/moderation': {
      id: '/_app/moderation'
      path: '/moderation'
      fullPath: '/moderation'
      preLoaderRoute: typeof AppModerationImport
      parentRoute: typeof AppImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsImport
      parentRoute: typeof AppImport
    }
    '/auth/twitch-callback': {
      id: '/auth/twitch-callback'
      path: '/twitch-callback'
      fullPath: '/auth/twitch-callback'
      preLoaderRoute: typeof AuthTwitchCallbackImport
      parentRoute: typeof AuthImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexImport
      parentRoute: typeof AppImport
    }
  }
}

// Create and export the route tree

interface AppRouteChildren {
  AppModerationRoute: typeof AppModerationRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppModerationRoute: AppModerationRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthTwitchCallbackRoute: typeof AuthTwitchCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthTwitchCallbackRoute: AuthTwitchCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/w': typeof WRoute
  '/moderation': typeof AppModerationRoute
  '/settings': typeof AppSettingsRoute
  '/auth/twitch-callback': typeof AuthTwitchCallbackRoute
  '/': typeof AppIndexRoute
}

export interface FileRoutesByTo {
  '/auth': typeof AuthRouteWithChildren
  '/w': typeof WRoute
  '/moderation': typeof AppModerationRoute
  '/settings': typeof AppSettingsRoute
  '/auth/twitch-callback': typeof AuthTwitchCallbackRoute
  '/': typeof AppIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/w': typeof WRoute
  '/_app/moderation': typeof AppModerationRoute
  '/_app/settings': typeof AppSettingsRoute
  '/auth/twitch-callback': typeof AuthTwitchCallbackRoute
  '/_app/': typeof AppIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/auth'
    | '/w'
    | '/moderation'
    | '/settings'
    | '/auth/twitch-callback'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/w'
    | '/moderation'
    | '/settings'
    | '/auth/twitch-callback'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/auth'
    | '/w'
    | '/_app/moderation'
    | '/_app/settings'
    | '/auth/twitch-callback'
    | '/_app/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  WRoute: typeof WRoute
}

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  WRoute: WRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_app",
        "/auth",
        "/w"
      ]
    },
    "/_app": {
      "filePath": "_app.tsx",
      "children": [
        "/_app/moderation",
        "/_app/settings",
        "/_app/"
      ]
    },
    "/auth": {
      "filePath": "auth.tsx",
      "children": [
        "/auth/twitch-callback"
      ]
    },
    "/w": {
      "filePath": "w.tsx"
    },
    "/_app/moderation": {
      "filePath": "_app.moderation.tsx",
      "parent": "/_app"
    },
    "/_app/settings": {
      "filePath": "_app.settings.tsx",
      "parent": "/_app"
    },
    "/auth/twitch-callback": {
      "filePath": "auth.twitch-callback.tsx",
      "parent": "/auth"
    },
    "/_app/": {
      "filePath": "_app.index.tsx",
      "parent": "/_app"
    }
  }
}
ROUTE_MANIFEST_END */
